"""
regenerate `draft/paper_draft.md` from `draft/latex/main.tex`.

The markdown draft is a companion mirror of the LaTeX submission. Keeping the
two in sync by hand is exactly the kind of manual step that lets a retracted
number survive in one file after being fixed in the other -- which has already
happened in this project's history (five stale claims were found surviving in
companion docs after main.tex had been corrected). This script makes the
markdown a mechanical function of the LaTeX, so the two cannot drift.

Run:  python3 code/52_sync_paper_draft_md.py
Check: `--check` exits non-zero if the file on disk differs from what would be
generated (useful as a pre-commit guard).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEX = ROOT / "draft" / "latex" / "main.tex"
MD = ROOT / "draft" / "paper_draft.md"


def strip_math(s):
    # $...$ -> plain text, with the most common macros spelled out.
    def repl(m):
        body = m.group(1)
        body = body.replace(r"\approx", "~").replace(r"\times", "x")
        body = body.replace(r"\geq", ">=").replace(r"\leq", "<=")
        body = body.replace(r"\to", "->").replace(r"\rightarrow", "->")
        body = body.replace(r"\pm", "+/-").replace(r"\ldots", "...")
        body = body.replace(r"\cdot", "*").replace(r"\emph", "")
        body = body.replace(r"\ln", "ln ").replace(r"\log", "log ")
        body = body.replace(r"\,", " ").replace(r"\;", " ").replace(r"\!", "")
        body = body.replace(r"\mathrm", "").replace(r"\left", "").replace(r"\right", "")
        body = re.sub(r"\\sqrt\{([^{}]*)\}", r"sqrt(\1)", body)
        body = re.sub(r"\\text\{([^{}]*)\}", r"\1", body)
        body = re.sub(r"\\mathbf\{([^{}]*)\}", r"\1", body)
        body = re.sub(r"\\(sigma|alpha|Phi|mu|kappa|Delta)\b", r"\1", body)
        body = body.replace("_{", "_").replace("^{", "^")
        body = body.replace("{", "").replace("}", "")
        body = body.replace("\\", "")
        return body
    return re.sub(r"\$([^$]*)\$", repl, s)


def convert_inline(s):
    s = re.sub(r"\\textbf\{((?:[^{}]|\{[^{}]*\})*)\}", r"**\1**", s)
    s = re.sub(r"\\(?:emph|textit)\{((?:[^{}]|\{[^{}]*\})*)\}", r"*\1*", s)
    s = re.sub(r"\\texttt\{((?:[^{}]|\{[^{}]*\})*)\}", r"`\1`", s)
    s = strip_math(s)
    s = s.replace(r"\_", "_").replace(r"\&", "&").replace(r"\%", "%")
    s = s.replace(r"\#", "#").replace(r"\$", "$")
    s = s.replace(r"\,", " ").replace(r"\;", " ").replace(r"\ ", " ")
    s = s.replace("---", "—").replace("--", "–")
    s = s.replace("``", '"').replace("''", '"')
    s = re.sub(r"\\label\{[^}]*\}", "", s)
    s = re.sub(r"\\ref\{[^}]*\}", "", s)
    s = re.sub(r"\\cite[a-z]*\{[^}]*\}", "", s)
    s = s.replace("\\ ", " ")
    s = re.sub(r"\\(?:medskip|noindent|smallskip|bigskip)\b\s*", "", s)
    return s


def main():
    tex = TEX.read_text()
    body = tex.split(r"\begin{document}", 1)[1]
    body = body.split(r"\end{document}", 1)[0]

    out = []
    title = re.search(r"\\title\{(.+?)\}\s*\n\s*\n", tex, re.S)
    title_text = re.sub(r"\s+", " ", title.group(1)).strip() if title else "(untitled)"
    out.append("# " + convert_inline(title_text))
    out.append("")
    out.append("> Companion markdown mirror of `draft/latex/main.tex`.")
    out.append("> AUTO-GENERATED by `code/52_sync_paper_draft_md.py` -- do not edit by hand;")
    out.append("> edit `main.tex` and re-run the script.")
    out.append("")

    section_n = 0
    subsection_n = 0
    subsubsection_n = 0
    # After \appendix, LaTeX letters the sections (A, B, C, ...) rather than
    # numbering them. The markdown mirror has to follow, or its headings stop
    # matching the cross-references the prose uses ("Appendix B.3").
    in_appendix = False
    appendix_n = 0
    sec_label = ""
    in_abstract = False
    in_itemize = False
    in_enumerate = False
    in_desc = False
    in_table = False
    in_figure = False
    enum_i = 0
    para = []

    def flush():
        nonlocal para
        if para:
            text = convert_inline(" ".join(para)).strip()
            text = re.sub(r"\s+", " ", text)
            if text:
                out.append(text)
                out.append("")
            para = []

    for raw in body.splitlines():
        line = raw.rstrip()
        s = line.strip()
        if s.startswith("%"):
            continue
        if s.startswith(r"\maketitle"):
            continue
        if s.startswith(r"\appendix"):
            flush(); in_appendix = True; continue

        if s.startswith(r"\begin{abstract}"):
            flush(); in_abstract = True
            out.append("## Abstract"); out.append(""); continue
        if s.startswith(r"\end{abstract}"):
            flush(); in_abstract = False; continue

        if s.startswith(r"\begin{table}") or s.startswith(r"\begin{tabular}") \
                or s.startswith(r"\begin{center}") or s.startswith(r"\begin{longtable}"):
            flush()
            in_table = True
            continue
        if s.startswith(r"\begin{figure}"):
            in_figure = True
        if in_table or in_figure:
            if s.startswith(r"\end{tabular}") or s.startswith(r"\end{center}") \
                    or s.startswith(r"\end{table}") or s.startswith(r"\end{figure}") \
                    or s.startswith(r"\end{longtable}"):
                # A center-wrapped tabular ends with \end{tabular} then \end{center};
                # closing on either is safe because nothing between them is content.
                in_table = in_figure = False
                out.append("")
                continue
            if s.startswith(r"\caption{"):
                flush()
                cap = re.sub(r"^\\caption\{", "", s)
                cap = re.sub(r"\}\s*$", "", cap)
                out.append("*" + convert_inline(cap).strip() + "*"); out.append("")
                continue
            # A row is any in-table line containing a column separator, even
            # if it starts with a formatting command like \textbf{...} (a
            # bold header row) -- checked BEFORE the generic backslash skip
            # below, which would otherwise swallow such rows whole. longtable
            # header/footer plumbing (\endfirsthead, \endhead, \endfoot,
            # \endlastfoot, \toprule, \bottomrule, a bare \label{...}\\, and
            # the \multicolumn{n}{l}{...} "(continued)" markers, none of which
            # contain "&") falls through to the final skip below.
            if in_table and "&" in s:
                cells = [convert_inline(c.strip().rstrip("\\")).strip()
                         for c in s.rstrip("\\").split("&")]
                out.append("| " + " | ".join(cells) + " |")
                continue
            if s.startswith(r"\midrule"):
                if out and out[-1].startswith("|"):
                    ncol = out[-1].count("|") - 1
                    out.append("|" + "---|" * ncol)
                continue
            if s.startswith("\\"):
                continue
            continue

        # Stray float/environment closers outside a table body.
        if s in (r"\end{center}", r"\end{tabular}", r"\bottomrule", r"\toprule",
                 r"\small", r"\centering", r"\normalsize", r"\end{longtable}"):
            continue

        m = re.match(r"\\section\{(.+)\}\s*$", s)
        if m:
            flush()
            name = convert_inline(m.group(1))
            if in_appendix:
                sec_label = chr(ord("A") + appendix_n)
                appendix_n += 1; subsection_n = 0; subsubsection_n = 0
                out.append(f"## Appendix {sec_label}. {name}")
            elif name.startswith("References"):
                out.append("## " + name)
            else:
                section_n += 1; subsection_n = 0
                sec_label = str(section_n)
                out.append(f"## {sec_label}. {name}")
            out.append(""); continue

        m = re.match(r"\\subsection\{(.+)\}\s*$", s)
        if m:
            flush(); subsection_n += 1; subsubsection_n = 0
            out.append(f"### {sec_label}.{subsection_n} " + convert_inline(m.group(1)))
            out.append(""); continue

        # Unnumbered subsection (\subsection*{...}) -- used inside the appendix.
        m = re.match(r"\\subsection\*\{(.+)\}\s*$", s)
        if m:
            flush()
            out.append("### " + convert_inline(m.group(1)))
            out.append(""); continue

        m = re.match(r"\\subsubsection\{(.+)\}\s*$", s)
        if m:
            flush(); subsubsection_n += 1
            out.append(f"#### {sec_label}.{subsection_n}.{subsubsection_n} "
                       + convert_inline(m.group(1)))
            out.append(""); continue

        if s.startswith(r"\begin{itemize}"):
            flush(); in_itemize = True; continue
        if s.startswith(r"\end{itemize}"):
            flush(); in_itemize = False; out.append(""); continue
        if s.startswith(r"\begin{enumerate}"):
            flush(); in_enumerate = True; enum_i = 0; continue
        if s.startswith(r"\end{enumerate}"):
            flush(); in_enumerate = False; out.append(""); continue
        if s.startswith(r"\begin{description}"):
            flush(); in_desc = True; continue
        if s.startswith(r"\end{description}"):
            flush(); in_desc = False; out.append(""); continue

        if in_desc and s.startswith(r"\item["):
            flush()
            m2 = re.match(r"\\item\[(.*?)\]\s*(.*)$", s)
            para = [f"__DESCITEM__{m2.group(1)}__ {m2.group(2)}"]
            continue
        if (in_itemize or in_enumerate) and s.startswith(r"\item"):
            flush()
            rest = s[len(r"\item"):].strip()
            if in_enumerate:
                enum_i += 1
                para = [f"__ENUM__{enum_i}__ {rest}"]
            else:
                para = [f"__BULLET__ {rest}"]
            continue

        if not s:
            flush(); continue

        para.append(s)

    flush()

    text = "\n".join(out)
    text = re.sub(r"__DESCITEM__(.*?)__ ", lambda m: f"- **{m.group(1)}** ", text)
    text = re.sub(r"__ENUM__(\d+)__ ", lambda m: f"{m.group(1)}. ", text)
    text = text.replace("__BULLET__ ", "- ")
    text = re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"

    if "--check" in sys.argv:
        current = MD.read_text() if MD.exists() else ""
        if current != text:
            print("OUT OF SYNC: draft/paper_draft.md does not match main.tex.")
            print("Run: python3 code/52_sync_paper_draft_md.py")
            return 1
        print("in sync")
        return 0

    MD.write_text(text)
    heads = [l for l in text.splitlines() if l.startswith("#")]
    print(f"Wrote {MD} ({len(text)} chars, {len(heads)} headers)")
    for h in heads:
        print("  " + h)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
